build(CMake): support running tests with ctest
BLAKE3-team/BLAKE3 pull request #405
Opened 2024-07-02 23:45 UTC by matoro

Adds the ability to run the test suite via `ctest`.  Works with both in-source and out-of-source builds.  Respects user flags, and builds SIMD into the tests corresponding to whatever was used to build the library.  Does not interfere with the ability to run tests the old way.

2024-07-03 07:19 UTC, BurningEnlightenment requested changes
Building tests should always be optional. Please add an option `BUILD_TESTING` or `BLAKE3_BUILD_TESTING`, conditionally call `enable_testing()`, and conditionally build the test target.

I'll defer to @oconnor663 as to whether we want to integrate the test environment with CMake.

2024-07-03 07:19 UTC, BurningEnlightenment commented on c/CMakeLists.txt
> +add_test(test_vectors "${CMAKE_CURRENT_SOURCE_DIR}/test.py" WORKING_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}")
I think we should `find_package(PYTHON)` and invoke the python executable with the script in order to allow the user to specify the python installation.

2024-07-04 21:49 UTC, matoro commented
Sure thing, both suggestions done.

2024-07-29 15:03 UTC, arthurzam commented
ping?

It would really help as at Gentoo Linux.

2024-07-30 08:33 UTC, BurningEnlightenment approved these changes
An `option(BLAKE3_BUILD_TESTING …` would be nice to have for the GUI people. However, I'm fine with this as is. Thanks for the contribution 🙏 

@oconnor663 still needs to decide, whether we want this or not.

2025-04-19 07:59 UTC, BurningEnlightenment commented
I believe this has been superseeded by the TBB PR

2025-04-19 07:59 UTC, closed without merging